### ISSUE TITLE
Multimodal RAG

### ISSUE THREAD

**Issue by jmstadt** [DanielWarfield1/MLWritingAndResearch#2]
Hi Daniel, great Medium post on Multimodal RAG.  Thank you for sharing and also thank you for providing the Colab notebook.  I was able to reproduce your work.  However I noticed that regardless of what I did, the cosine similarity score was always low for the picture embedding.  I replaced your picture with another picture that I knew was the only thing that had the answer to a specific question.  The cosine similarity score stayed low compared to the audio and text and Gemini responded that it could not answer the question.  When I removed the if statement and just used the picture embedding, Gemini did answer the question using the image.  Curious if you have been able to get a result where the picture provides the answer?  I am wondering if CLIP embeddings and Torch cosine similarity do not play nice with each other?  Regardless, way impressed and very appreciative of your sharing this.

**Comment by DanielWarfield1** [comment]
Hey Jmstadt! Great question, and I appreciate the depth of review.

The point of that example was to "got through the paces" so to speak. I didn't spend time choosing the right embedding, or experimenting with different alignment strategies. If you were to use a similar approach in a production setting, where you actually cared about performance, then I imagine a significant effort would go into ensuring allignment; either by building on pre-trained encoders or making your own.

I do have an article on CLIP, if you're curious about that.
